config/routes.rb
Rails.application.routes.draw do
  resources :observationbiometrics
  resources :treatments
  resources :diseases
  get 'pages/about'

  get 'pages/homepage'

  root to: redirect('/pages/homepage')

  resources :cats

end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
  belongs_to :disease
  has_many :observationbiometrics

end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :set_treatment, only: [:show, :edit, :update, :destroy]

  # GET /treatments
  # GET /treatments.json
  def index
    @treatments = Treatment.all
  end

  # GET /treatments/1
  # GET /treatments/1.json
  def show
    @observationbiometrics = @treatment.observationbiometrics.all
    @observationbiometric = @treatment.observationbiometrics.build
  end

  # GET /treatments/new
  def new
    @treatment = Treatment.new
  end

  # GET /treatments/1/edit
  def edit
  end

  # POST /treatments
  # POST /treatments.json
  def create
    @treatment = Treatment.new(treatment_params)

    respond_to do |format|
      if @treatment.save
        format.html { redirect_to @treatment, notice: 'Treatment was successfully created.' }
        format.json { render :show, status: :created, location: @treatment }
      else
        format.html { render :new }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatments/1
  # PATCH/PUT /treatments/1.json
  def update
    respond_to do |format|
      if @treatment.update(treatment_params)
        format.html { redirect_to @treatment, notice: 'Treatment was successfully updated.' }
        format.json { render :show, status: :ok, location: @treatment }
      else
        format.html { render :edit }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1
  # DELETE /treatments/1.json
  def destroy
    @treatment.destroy
    respond_to do |format|
      format.html { redirect_to treatments_url, notice: 'Treatment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment
      @treatment = Treatment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def treatment_params
      params.require(:treatment).permit(:disease_id, :startdate, :enddate, :totalweeks, :medicine, :dose, :device, :surgery, :treatmentcomplete)
    end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/_form.html.erb
<%= form_for(@treatment) do |f| %>
  <% if @treatment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@treatment.errors.count, "error") %> prohibited this treatment from being saved:</h2>

      <ul>
      <% @treatment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.hidden_field :disease_id %>
<!--   <div class="field">
    <%= f.label :startdate, "Start Date" %><br>
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate, "End Date" %><br>
    <%= f.date_select :enddate %>
  </div> -->
  <div class="field">
    <%= f.label :totalweeks, "Total Weeks" %><br>
    <%= f.number_field :totalweeks %>
  </div>
  <div class="field">
    <%= f.label :medicine %><br>
    <%= f.text_area :medicine %>
  </div>
  <div class="field">
    <%= f.label :dose %><br>
    <%= f.text_area :dose %>
  </div>
  <div class="field">
    <%= f.label :device %><br>
    <%= f.text_area :device %>
  </div>
  <div class="field">
    <%= f.label :surgery %><br>
    <%= f.text_area :surgery %>
  </div>
  <div class="field">
    <%= f.label :treatmentcomplete, "Treatment Completed" %><br>
    <%= f.check_box :treatmentcomplete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/treatments/_suggested.html.erb
<h3>Suggested Treatment</h3>

  <p><strong>Medicine:</strong> GS-441524</p>
  <p><strong>Dose:</strong> 2.0 to 4.0 mg/kg q24h</p>
  <p><strong>Weeks:</strong> While condition is active or longer as determiend by veterinarian</p>

<div class="container">
  <div class="row">
    <div class="col">
      <%= if FileTest.exist?("#{Rails.root}/app/assets/images/GS-441524/GS-441524DailyTempAverage.png")
        image_tag "GS-441524/GS-441524DailyTempAverage.png", size: "400"
      else 
        image_tag "GS-441524/FIPDailyTempAverage.png", size: "400"
      end %>
    </div>
    <div class="col">
      <%= if FileTest.exist?("#{Rails.root}/app/assets/images/GS-441524/GS-441524PCVAverage.png")
        image_tag "GS-441524/GS-441524PCVAverage.png", size: "400"
      else 
        image_tag "GS-441524/FIPPCVAverage.png", size: "400"
      end %>
    </div>
    <div class="col">
      <%= if FileTest.exist?("#{Rails.root}/app/assets/images/GS-441524/GS-441524WeeklyLymphocytesAverage.png")
        image_tag "GS-441524/GS-441524WeeklyLymphocytesAverage.png", size: "400"
      else 
        image_tag "GS-441524/FIPWeeklyLymphocytesAverage.png", size: "400"
      end %>
    </div>
    <div class="col">
      <%= if FileTest.exist?("#{Rails.root}/app/assets/images/GS-441524/GS-441524WeeklyWhiteBloodCellsAverage.png")
        image_tag "GS-441524/GS-441524WeeklyWhiteBloodCellsAverage.png", size: "400"
      else 
        image_tag "GS-441524/FIPWeeklyWhiteBloodCellsAverage.png", size: "400"
      end %>
    </div>
  </div>
</div>

app/views/treatments/edit.html.erb
<h1>Editing Treatment</h1>

<%= render 'form' %>

<%= link_to 'Show', @treatment %> |
<%= link_to 'Back', treatments_path %>

app/views/treatments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Treatments</h1>

<table>
  <thead>
    <tr>
      <th>Disease</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Totalweeks</th>
      <th>Medicine</th>
      <th>Dose</th>
      <th>Device</th>
      <th>Surgery</th>
      <th>Treatmentcomplete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @treatments.each do |treatment| %>
      <tr>
        <td><%= treatment.disease_id %></td>
        <td><%= treatment.startdate %></td>
        <td><%= treatment.enddate %></td>
        <td><%= treatment.totalweeks %></td>
        <td><%= treatment.medicine %></td>
        <td><%= treatment.dose %></td>
        <td><%= treatment.device %></td>
        <td><%= treatment.surgery %></td>
        <td><%= treatment.treatmentcomplete %></td>
        <td><%= link_to 'Show', treatment %></td>
        <td><%= link_to 'Edit', edit_treatment_path(treatment) %></td>
        <td><%= link_to 'Destroy', treatment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Treatment', new_treatment_path %>

app/views/treatments/new.html.erb
<h1>New Treatment</h1>

<%= render 'form' %>

<%= link_to 'Back', treatments_path %>

app/views/treatments/show.html.erb
<p id="notice"><%= notice %></p>
<h3>Treatment Plan</h3>

<!-- <p>
  <strong>Disease:</strong>
  <%= @treatment.disease_id %>
</p> -->

<!-- <p>
  <strong>Start date:</strong>
  <%= @treatment.startdate %>
</p>

<p>
  <strong>End date:</strong>
  <%= @treatment.enddate %>
</p> -->

<p>
  <strong>Total weeks:</strong>
  <%= @treatment.totalweeks %>
</p>

<p>
  <strong>Medicine:</strong>
  <%= @treatment.medicine %>
</p>

<p>
  <strong>Dose:</strong>
  <%= @treatment.dose %>
</p>

<p>
  <strong>Device:</strong>
  <%= @treatment.device %>
</p>

<p>
  <strong>Surgery:</strong>
  <%= @treatment.surgery %>
</p>

<p>
  <strong>Treatment completed:</strong>
  <%= @treatment.treatmentcomplete %>
</p>

<p><%= link_to 'Edit', edit_treatment_path(@treatment) %> | 
<a href='/diseases/<%= @treatment.disease_id %>'>View Condition being treated</a> |  
<%= link_to 'View all Pets\' Treatment Plans', treatments_path %>  
</p>

<h3>Observation Biometrics</h3>
<% @observationbiometrics.each do |observationbiometric| %>
  <div>

    <strong>Daily Temp F</strong>
    <br>
    <p><strong>Before treatment </strong><%= observationbiometric.Day0TempF %></p>
    <p><strong>Day 1 </strong><%= observationbiometric.Day1TempF %></p>
    <p><strong>Day 2 </strong><%= observationbiometric.Day2TempF %></p>
    <p><strong>Day 3 </strong><%= observationbiometric.Day3TempF %></p>
    <p><strong>Day 4 </strong><%= observationbiometric.Day4TempF %></p>
    <p><strong>Day 5 </strong><%= observationbiometric.Day5TempF %></p>
    <br>
    <strong>Weekly White Blood Metrics</strong>
    <br>
    <p><strong>Before treatment </strong><%= observationbiometric.Week0WhiteBlood %></p>
    <p><strong>Week 1 </strong><%= observationbiometric.Week1WhiteBlood %></p>
    <p><strong>Week 2 </strong><%= observationbiometric.Week2WhiteBlood %></p>
    <p><strong>Week 3 </strong><%= observationbiometric.Week3WhiteBlood %></p>
    <p><strong>Week 4 </strong><%= observationbiometric.Week4WhiteBlood %></p>
    <p><strong>Week 5 </strong><%= observationbiometric.Week5WhiteBlood %></p>
    <p><strong>Week 6 </strong><%= observationbiometric.Week6WhiteBlood %></p>
    <p><strong>Week 7 </strong><%= observationbiometric.Week7WhiteBlood %></p>
    <p><strong>Week 8 </strong><%= observationbiometric.Week8WhiteBlood %></p>
    <p><strong>Week 9 </strong><%= observationbiometric.Week9WhiteBlood %></p>
    <p><strong>Week 10 </strong><%= observationbiometric.Week10WhiteBlood %></p>
    <p><strong>Week 11 </strong><%= observationbiometric.Week11WhiteBlood %></p>
    <p><strong>Week 12 </strong><%= observationbiometric.Week12WhiteBlood %></p>
    <br>
    <strong>Weekly Lymphocytes Metrics</strong>
    <br>
    <p><strong>Before treatment </strong><%= observationbiometric.Week0lymphocytes %></p>
    <p><strong>Week 1 </strong><%= observationbiometric.Week1lymphocytes %></p>
    <p><strong>Week 2 </strong><%= observationbiometric.Week2lymphocytes %></p>
    <p><strong>Week 3 </strong><%= observationbiometric.Week3lymphocytes %></p>
    <p><strong>Week 4 </strong><%= observationbiometric.Week4lymphocytes %></p>
    <p><strong>Week 5 </strong><%= observationbiometric.Week5lymphocytes %></p>
    <p><strong>Week 6 </strong><%= observationbiometric.Week6lymphocytes %></p>
    <p><strong>Week 7 </strong><%= observationbiometric.Week7lymphocytes %></p>
    <p><strong>Week 8 </strong><%= observationbiometric.Week8lymphocytes %></p>
    <p><strong>Week 9 </strong><%= observationbiometric.Week9lymphocytes %></p>
    <p><strong>Week 10 </strong><%= observationbiometric.Week10lymphocytes %></p>    
    <p><strong>Week 11 </strong><%= observationbiometric.Week11lymphocytes %></p>
    <p><strong>Week 12 </strong><%= observationbiometric.Week12lymphocytes %></p>
    <br>
    <strong>Weekly PCV Metrics</strong>
    <br>
    <p><strong>Week 1 </strong><%= observationbiometric.Week1PCV %></p>
    <p><strong>Week 2 </strong><%= observationbiometric.Week2PCV %></p>
    <p><strong>Week 3 </strong><%= observationbiometric.Week3PCV %></p>
    <p><strong>Week 4 </strong><%= observationbiometric.Week4PCV %></p>
    <p><strong>Week 5 </strong><%= observationbiometric.Week5PCV %></p>
    <p><strong>Week 6 </strong><%= observationbiometric.Week6PCV %></p>
    <p><strong>Week 7 </strong><%= observationbiometric.Week7PCV %></p>
    <p><strong>Week 8 </strong><%= observationbiometric.Week8PCV %></p>
    <p><strong>Week 9 </strong><%= observationbiometric.Week9PCV %></p>
    <p><strong>Week 10 </strong><%= observationbiometric.Week10PCV %></p>
    <p><strong>Week 11 </strong><%= observationbiometric.Week11PCV %></p>
    <p><strong>Week 12 </strong><%= observationbiometric.Week12PCV %></p>
    <br>
    <p><%= link_to 'Delete', observationbiometric_path(observationbiometric), method: :delete, data: { confirm: 'Are you sure?' } %> | 
    <a href='/observationbiometrics/<%= observationbiometric.id %>/edit'>Edit</a></p>
  </div>
<% end %>



<button>Add Observation Biometrics</button><br><br>
<div id='observationbiometricform'>
  <%= render partial: 'observationbiometrics/form', locals: { observationbiometric: @observationbiometric } %>
</div>

<!-- To Do: Move this code out -->
<script>$('#observationbiometricform').hide();</script>
<script>
$(document).ready(function(){
  $("button").click(function(){
    $("#observationbiometricform").toggle();
  });
});
</script>