config/routes.rb
Rails.application.routes.draw do
  resources :observationbiometrics
  resources :treatments
  resources :diseases
  get 'pages/about'

  get 'pages/homepage'

  root to: redirect('/pages/homepage')

  resources :cats

end

app/controllers/diseases_controller.rb
class DiseasesController < ApplicationController
  before_action :set_disease, only: [:show, :edit, :update, :destroy]

  # GET /diseases
  # GET /diseases.json
  def index
    @diseases = Disease.all
  end

  # GET /diseases/1
  # GET /diseases/1.json
  def show
    @treatments = @disease.treatments.all
    @treatment = @disease.treatments.build
  end

  # GET /diseases/new
  def new
    @disease = Disease.new
  end

  # GET /diseases/1/edit
  def edit
  end

  # POST /diseases
  # POST /diseases.json
  def create
    @disease = Disease.new(disease_params)

    respond_to do |format|
      if @disease.save
        format.html { redirect_to @disease, notice: 'Disease was successfully created.' }
        format.json { render :show, status: :created, location: @disease }
      else
        format.html { render :new }
        format.json { render json: @disease.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diseases/1
  # PATCH/PUT /diseases/1.json
  def update
    respond_to do |format|
      if @disease.update(disease_params)
        format.html { redirect_to @disease, notice: 'Disease was successfully updated.' }
        format.json { render :show, status: :ok, location: @disease }
      else
        format.html { render :edit }
        format.json { render json: @disease.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diseases/1
  # DELETE /diseases/1.json
  def destroy
    @disease.destroy
    respond_to do |format|
      format.html { redirect_to diseases_url, notice: 'Disease was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disease
      @disease = Disease.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disease_params
      params.require(:disease).permit(:cat_id, :veterinarian, :dateofdiagnosis, :condition, :conditionform, :conditionrelapse, :remission, :remissiondate)
    end
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/views/diseases/_form.html.erb
<%= form_for(@disease) do |f| %>
  <% if @disease.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disease.errors.count, "error") %> prohibited this disease from being saved:</h2>

      <ul>
      <% @disease.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :cat_id %>
  <div class="field">
    <%= f.label :veterinarian %><br>
    <%= f.text_field :veterinarian %>
  </div>
  <div class="field">
    <%= f.label :dateofdiagnosis, "Date of diagnosis" %><br>
    <%= f.date_select :dateofdiagnosis %>
  </div>
  <div class="field">
    <%= f.label :condition %><br>
    <%= f.text_area :condition %>
  </div>
  <div class="field">
    <%= f.label :conditionform, "Condition form" %><br>
    <%= f.text_area :conditionform %>
  </div>
  <div class="field">
    <%= f.label :conditionrelapse, "Condition relapsed" %><br>
    <%= f.check_box :conditionrelapse %>
  </div>
  <div class="field">
    <%= f.label :remission %><br>
    <%= f.check_box :remission %>
  </div>
<!--   <div class="field" id="remissiondate">
    <%= f.label :remissiondate %><br>
    <%= f.date_select :remissiondate %>
  </div> -->
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/diseases/edit.html.erb
<h1>Editing Condition</h1>

<%= render 'form' %>

<%= link_to 'Show', @disease %> |

<a href='/cats/<%= @disease.cat_id %>'>Back to Cat details</a>

app/views/diseases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Conditions of all Pets</h1>

<table>
  <thead>
    <tr>
<!--       <th>Cat</th> -->
      <th>Veterinarian</th>
      <th> | Date of diagnosis</th>
      <th> | Condition</th>
      <th> | Condition form</th>
      <th> | Condition relapse</th>
      <th> | Remission</th>
      <th> | Remission date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diseases.each do |disease| %>
      <tr>
<!--         <td><%= disease.cat_id %></td> -->
        <td><%= disease.veterinarian %></td>
        <td> | <%= disease.dateofdiagnosis %></td>
        <td> | <%= disease.condition %></td>
        <td> | <%= disease.conditionform %></td>
        <td> | <%= disease.conditionrelapse %></td>
        <td> | <%= disease.remission %></td>
        <td> | <%= disease.remissiondate %></td>
        <td><%= link_to 'Show', disease %></td>
        <td><%= link_to 'Edit', edit_disease_path(disease) %></td>
        <td><%= link_to 'Destroy', disease, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Disease', new_disease_path %> -->

app/views/diseases/new.html.erb
<h1>New Disease</h1>

<%= render 'form' %>

<%= link_to 'Back', diseases_path %>

app/views/diseases/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Condition</h3>

<%= link_to 'Edit this record', edit_disease_path(@disease) %> | 
<a href='/cats/<%= @disease.cat_id %>'>See this Cat's details</a> | <%= link_to 'View all Pets\' condition records', diseases_path %> 

<!-- <p>
  <strong>Cat:</strong>
  <%= @disease.cat_id %>
</p> -->
<br><br>
<p>
  <strong>Veterinarian:</strong>
  <%= @disease.veterinarian %>
</p>

<p>
  <strong>Date of Diagnosis:</strong>
  <%= @disease.dateofdiagnosis %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @disease.condition %>
</p>

<p>
  <strong>Condition form:</strong>
  <%= @disease.conditionform %>
</p>

<p>
  <strong>Condition relapsed:</strong>
  <%= @disease.conditionrelapse %>
</p>

<p>
  <strong>Remission:</strong>
  <%= @disease.remission %>
</p>

<!-- <p>
  <strong>Remission date:</strong>
  <%= @disease.remissiondate %>
</p> -->

<% if @disease.condition == 'Feline infectious peritonitis'%>
  <div id='suggestedtreatment'>
    <br>
    <%= render partial: 'treatments/suggested', locals: { treatment: @treatment } %>
    <br><br>
  </div>
<% end %>




<h3>Treatment Plans</h3>
<% @treatments.each do |treatment| %>
  <div>
    <br>
<!--     <p><strong>Start date: </strong><%= treatment.startdate %></p>
    <p><strong>End date: </strong><%= treatment.enddate %></p> -->
    <p><strong>Total weeks: </strong><%= treatment.totalweeks %></p>
    <p><strong>Medicine: </strong><%= treatment.medicine %></p>
    <p><strong>Dose: </strong><%= treatment.dose %></p>
    <p><strong>Device: </strong><%= treatment.device %></p>
    <p><strong>Surgery: </strong><%= treatment.surgery %></p>
    <p><strong>Treatment completed: </strong><%= treatment.treatmentcomplete %></p>
    <p><%= link_to 'Delete', treatment_path(treatment), method: :delete, data: { confirm: 'Are you sure?' } %> | <a href='/treatments/<%= treatment.id %>/edit'>Edit</a> | 
    <a href='/treatments/<%= treatment.id %>'>Review biometrics while on plan</a>
    </p>
  </div>
<% end %><br>

<button>Add Treatment</button><br><br>
<div id='treatmentform'>
  <%= render partial: 'treatments/form', locals: { treatment: @treatment } %>
</div>

<!-- To Do: Move this code out -->
<script>$('#treatmentform').hide();</script>
<script>
$(document).ready(function(){
  $("button").click(function(){
    $("#treatmentform").toggle();
  });
});
</script>