config/routes.rb
Rails.application.routes.draw do
  resources :observationbiometrics
  resources :treatments
  resources :diseases
  get 'pages/about'

  get 'pages/homepage'

  root to: redirect('/pages/homepage')

  resources :cats

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  has_many :diseases

  mount_uploader :picture, PictureUploader




end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all

  end

  # GET /cats/1
  # GET /cats/1.json
  def show
    @diseases = @cat.diseases.all
    @disease = @cat.diseases.build
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:user_id, :name, :description, :picture, :dateofbirth, :breed, :sex, :origin, :dead, :causeofdeath)
    end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<%= form_for(@cat) do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--   <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div> -->
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :dateofbirth, "Date of Birth" %><br>
    <%= f.date_select :dateofbirth %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>    
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :dead %><br>
    <%= f.check_box :dead %>
  </div>
  <div class="field">
    <%= f.label :causeofdeath, "Cause of Death" %><br>
    <%= f.text_area :causeofdeath %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cats</h1>

<table>
  <thead>
    <tr>
<!--       <th>User</th> -->
      <th>Name</th>
      <th> | Description</th>
      <th> | Picture</th>
      <th> | Date of birth</th>
      <th> | Breed</th>
      <th> | Sex</th>
      <th> | Origin</th>
      <th> | Dead</th>
      <th> | Cause of death</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
<!--         <td><%= cat.user_id %></td> -->
        <td><%= cat.name %></td>
        <td> | <%= cat.description %></td>
        <td> | <%= image_tag cat.picture_url, width: '100%' if cat.picture.present? %></td>
        <td> | <%= cat.dateofbirth %></td>
        <td> | <%= cat.breed %></td>
        <td> | <%= cat.sex %></td>
        <td> | <%= cat.origin %></td>
        <td> | <%= cat.dead %></td>
        <td> | <%= cat.causeofdeath %></td>
        <td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form' %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit cat details', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>
<br><br>

<p>
  <strong>Name:</strong>
  <%= @cat.name %>
</p>

  <% if (@cat.description != "") %>  
    <p> 
      <strong>Description:</strong>
        <%= @cat.description %>
    </p>
  <% else %>
  <% end %>

</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@cat.picture_url, width: 600) if @cat.picture.present? %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @cat.dateofbirth %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @cat.breed %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @cat.sex %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @cat.origin %>
</p>

<p>
  <strong>Dead:</strong>
  <%= @cat.dead %>
</p>

<p>
  <strong>Cause of death:</strong>
  <%= @cat.causeofdeath %>
</p>


<h3>Medical History</h3>
<% @diseases.each do |disease| %>
  <div>
    <strong><%= disease.dateofdiagnosis %></strong>
    <br>
    <p><strong>Condition:</strong> <%= disease.condition %></p>
    <p><strong>Condition form:</strong> <%= disease.conditionform %></p>
    <p><strong>Relapsed:</strong> <%= disease.conditionrelapse %></p>
    <p><strong>In remission:</strong><%= disease.remission %></p>
    <p><strong>Who made diagnosis:</strong><%= disease.veterinarian %></p>
    <p><%= link_to 'Delete', disease_path(disease), method: :delete, data: { confirm: 'Are you sure?' } %> | <a href='/diseases/<%= disease.id %>/edit'>Edit</a> | <a href='/diseases/<%= disease.id %>'>Review treatment plan</a> </p>
  </div>
<% end %>
<br>

<button>Add Diagnosis</button><br><br>
<div id='diseaseform'>
  <%= render partial: 'diseases/form', locals: { disease: @disease } %>
</div>

<!-- To Do: Move this code out -->
<script>$('#diseaseform').hide();</script>
<script>
$(document).ready(function(){
  $("button").click(function(){
    $("#diseaseform").toggle();
  });
});
</script>