config/routes.rb
Rails.application.routes.draw do
  resources :observationbiometrics
  resources :treatments
  resources :diseases
  get 'pages/about'

  get 'pages/homepage'

  root to: redirect('/pages/homepage')

  resources :cats

end

app/models/observationbiometric.rb
class Observationbiometric < ActiveRecord::Base
  belongs_to :treatment
end

app/controllers/observationbiometrics_controller.rb
class ObservationbiometricsController < ApplicationController
  before_action :set_observationbiometric, only: [:show, :edit, :update, :destroy]

  # GET /observationbiometrics
  # GET /observationbiometrics.json
  def index
    @observationbiometrics = Observationbiometric.all
  end

  # GET /observationbiometrics/1
  # GET /observationbiometrics/1.json
  def show
  end

  # GET /observationbiometrics/new
  def new
    @observationbiometric = Observationbiometric.new
  end

  # GET /observationbiometrics/1/edit
  def edit
  end

  # POST /observationbiometrics
  # POST /observationbiometrics.json
  def create
    @observationbiometric = Observationbiometric.new(observationbiometric_params)

    respond_to do |format|
      if @observationbiometric.save
        format.html { redirect_to @observationbiometric, notice: 'Observationbiometric was successfully created.' }
        format.json { render :show, status: :created, location: @observationbiometric }
      else
        format.html { render :new }
        format.json { render json: @observationbiometric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /observationbiometrics/1
  # PATCH/PUT /observationbiometrics/1.json
  def update
    respond_to do |format|
      if @observationbiometric.update(observationbiometric_params)
        format.html { redirect_to @observationbiometric, notice: 'Observationbiometric was successfully updated.' }
        format.json { render :show, status: :ok, location: @observationbiometric }
      else
        format.html { render :edit }
        format.json { render json: @observationbiometric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /observationbiometrics/1
  # DELETE /observationbiometrics/1.json
  def destroy
    @observationbiometric.destroy
    respond_to do |format|
      format.html { redirect_to observationbiometrics_url, notice: 'Observationbiometric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_observationbiometric
      @observationbiometric = Observationbiometric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def observationbiometric_params
      params.require(:observationbiometric).permit(:treatment_id, :Day0TempF, :Day1TempF, :Day2TempF, :Day3TempF, :Day4TempF, :Day5TempF, :Week0WhiteBlood, :Week1WhiteBlood, :Week2WhiteBlood, :Week3WhiteBlood, :Week4WhiteBlood, :Week5WhiteBlood, :Week6WhiteBlood, :Week7WhiteBlood, :Week8WhiteBlood, :Week9WhiteBlood, :Week10WhiteBlood, :Week11WhiteBlood, :Week12WhiteBlood, :Week0lymphocytes, :Week1lymphocytes, :Week2lymphocytes, :Week3lymphocytes, :Week4lymphocytes, :Week5lymphocytes, :Week6lymphocytes, :Week7lymphocytes, :Week8lymphocytes, :Week9lymphocytes, :Week10lymphocytes, :Week11lymphocytes, :Week12lymphocytes, :Week1PCV, :Week2PCV, :Week3PCV, :Week4PCV, :Week5PCV, :Week6PCV, :Week7PCV, :Week8PCV, :Week9PCV, :Week10PCV, :Week11PCV, :Week12PCV)
    end
end

app/helpers/observationbiometrics_helper.rb
module ObservationbiometricsHelper
end

app/views/observationbiometrics/_form.html.erb
<%= form_for(@observationbiometric) do |f| %>
  <% if @observationbiometric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@observationbiometric.errors.count, "error") %> prohibited this observationbiometric from being saved:</h2>

      <ul>
      <% @observationbiometric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.hidden_field :treatment_id %>
  <div class="field">
    <%= f.label :Day0TempF, "Before treatment Temp in F" %><br>
    <%= f.number_field :Day0TempF %>
  </div>
  <div class="field">
    <%= f.label :Day1TempF, "Day 1 Temp in F" %><br>
    <%= f.number_field :Day1TempF %>
  </div>
  <div class="field">
    <%= f.label :Day2TempF, "Day 2 Temp in F" %><br>
    <%= f.number_field :Day2TempF %>
  </div>
  <div class="field">
    <%= f.label :Day3TempF, "Day 3 Temp in F" %><br>
    <%= f.number_field :Day3TempF %>
  </div>
  <div class="field">
    <%= f.label :Day4TempF, "Day 4 Temp in F" %><br>
    <%= f.number_field :Day4TempF %>
  </div>
  <div class="field">
    <%= f.label :Day5TempF, "Day 5 Temp in F" %><br>
    <%= f.number_field :Day5TempF %>
  </div>
  <div class="field">
    <%= f.label :Week0WhiteBlood, "White blood cell count before treatment" %><br>
    <%= f.number_field :Week0WhiteBlood %>
  </div>
  <div class="field">
    <%= f.label :Week1WhiteBlood, "White blood cell count week 1" %><br>
    <%= f.number_field :Week1WhiteBlood %>
  </div>
  <div class="field">
    <%= f.label :Week2WhiteBlood, "White blood cell count week 2" %><br>
    <%= f.number_field :Week2WhiteBlood %>
  </div>
  <div class="field">
    <%= f.label :Week3WhiteBlood, "White blood cell count week 3" %><br>
    <%= f.number_field :Week3WhiteBlood %>
  </div>
  <div class="field">
    <%= f.label :Week4WhiteBlood, "White blood cell count week 4" %><br>
    <%= f.number_field :Week4WhiteBlood %>
  </div>
  <div class="field">
    <%= f.label :Week5WhiteBlood, "White blood cell count week 5" %><br>
    <%= f.number_field :Week5WhiteBlood %>
  </div>
  <div class="field">
    <%= f.label :Week6WhiteBlood, "White blood cell count week 6" %><br>
    <%= f.number_field :Week6WhiteBlood %>
  </div>
  <div class="field">
    <%= f.label :Week7WhiteBlood, "White blood cell count week 7" %><br>
    <%= f.number_field :Week7WhiteBlood %>
  </div>
  <div class="field">
    <%= f.label :Week8WhiteBlood, "White blood cell count week 8" %><br>
    <%= f.number_field :Week8WhiteBlood %>
  </div>
  <div class="field">
    <%= f.label :Week9WhiteBlood, "White blood cell count week 9" %><br>
    <%= f.number_field :Week9WhiteBlood %>
  </div>
  <div class="field">
    <%= f.label :Week10WhiteBlood, "White blood cell count week 10" %><br>
    <%= f.number_field :Week10WhiteBlood %>
  </div>
  <div class="field">
    <%= f.label :Week11WhiteBlood, "White blood cell count week 11" %><br>
    <%= f.number_field :Week11WhiteBlood %>
  </div>
  <div class="field">
    <%= f.label :Week12WhiteBlood, "White blood cell count week 12" %><br>
    <%= f.number_field :Week12WhiteBlood %>
  </div>
  <div class="field">
    <%= f.label :Week0lymphocytes, "Absolute blood lymphocyte count before treatment" %><br>
    <%= f.number_field :Week0lymphocytes %>
  </div>
  <div class="field">
    <%= f.label :Week1lymphocytes, "Absolute blood lymphocyte count week 1" %><br>
    <%= f.number_field :Week1lymphocytes %>
  </div>
  <div class="field">
    <%= f.label :Week2lymphocytes, "Absolute blood lymphocyte count week 2" %><br>
    <%= f.number_field :Week2lymphocytes %>
  </div>
  <div class="field">
    <%= f.label :Week3lymphocytes, "Absolute blood lymphocyte count week 3" %><br>
    <%= f.number_field :Week3lymphocytes %>
  </div>
  <div class="field">
    <%= f.label :Week4lymphocytes, "Absolute blood lymphocyte count week 4" %><br>
    <%= f.number_field :Week4lymphocytes %>
  </div>
  <div class="field">
    <%= f.label :Week5lymphocytes, "Absolute blood lymphocyte count week 5" %><br>
    <%= f.number_field :Week5lymphocytes %>
  </div>
  <div class="field">
    <%= f.label :Week6lymphocytes, "Absolute blood lymphocyte count week 6" %><br>
    <%= f.number_field :Week6lymphocytes %>
  </div>
  <div class="field">
    <%= f.label :Week7lymphocytes, "Absolute blood lymphocyte count week 7" %><br>
    <%= f.number_field :Week7lymphocytes %>
  </div>
  <div class="field">
    <%= f.label :Week8lymphocytes, "Absolute blood lymphocyte count week 8" %><br>
    <%= f.number_field :Week8lymphocytes %>
  </div>
  <div class="field">
    <%= f.label :Week9lymphocytes, "Absolute blood lymphocyte count week 9" %><br>
    <%= f.number_field :Week9lymphocytes %>
  </div>
  <div class="field">
    <%= f.label :Week10lymphocytes, "Absolute blood lymphocyte count week 10" %><br>
    <%= f.number_field :Week10lymphocytes %>
  </div>
  <div class="field">
    <%= f.label :Week11lymphocytes, "Absolute blood lymphocyte count week 11" %><br>
    <%= f.number_field :Week11lymphocytes %>
  </div>
  <div class="field">
    <%= f.label :Week12lymphocytes, "Absolute blood lymphocyte count week 12" %><br>
    <%= f.number_field :Week12lymphocytes %>
  </div>
  <div class="field">
    <%= f.label :Week1PCV, "Packed Cell volume (PCV) week 1" %><br>
    <%= f.number_field :Week1PCV %>
  </div>
  <div class="field">
    <%= f.label :Week2PCV, "Packed Cell volume (PCV) week 2" %><br>
    <%= f.number_field :Week2PCV %>
  </div>
  <div class="field">
    <%= f.label :Week3PCV, "Packed Cell volume (PCV) week 3" %><br>
    <%= f.number_field :Week3PCV %>
  </div>
  <div class="field">
    <%= f.label :Week4PCV, "Packed Cell volume (PCV) week 4" %><br>
    <%= f.number_field :Week4PCV %>
  </div>
  <div class="field">
    <%= f.label :Week5PCV, "Packed Cell volume (PCV) week 5" %><br>
    <%= f.number_field :Week5PCV %>
  </div>
  <div class="field">
    <%= f.label :Week6PCV, "Packed Cell volume (PCV) week 6" %><br>
    <%= f.number_field :Week6PCV %>
  </div>
  <div class="field">
    <%= f.label :Week7PCV, "Packed Cell volume (PCV) week 7" %><br>
    <%= f.number_field :Week7PCV %>
  </div>
  <div class="field">
    <%= f.label :Week8PCV, "Packed Cell volume (PCV) week 8" %><br>
    <%= f.number_field :Week8PCV %>
  </div>
  <div class="field">
    <%= f.label :Week9PCV, "Packed Cell volume (PCV) week 9" %><br>
    <%= f.number_field :Week9PCV %>
  </div>
  <div class="field">
    <%= f.label :Week10PCV, "Packed Cell volume (PCV) week 10" %><br>
    <%= f.number_field :Week10PCV %>
  </div>
  <div class="field">
    <%= f.label :Week11PCV, "Packed Cell volume (PCV) week 11" %><br>
    <%= f.number_field :Week11PCV %>
  </div>
  <div class="field">
    <%= f.label :Week12PCV, "Packed Cell volume (PCV) week 12" %><br>
    <%= f.number_field :Week12PCV %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/observationbiometrics/edit.html.erb
<h1>Editing Observation Biometrics</h1>

<%= link_to 'Show', @observationbiometric %> |
<%= link_to 'View all Observation Biometrics', observationbiometrics_path %> | <a href='/treatments/<%= @observationbiometric.treatment_id %>'>Back to treatment plan</a>

<%= render 'form' %>

app/views/observationbiometrics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Observationbiometrics</h1>

<table>
  <thead>
    <tr>
      <th>Treatment</th>
      <th>Day0tempf</th>
      <th>Day1tempf</th>
      <th>Day2tempf</th>
      <th>Day3tempf</th>
      <th>Day4tempf</th>
      <th>Day5tempf</th>
      <th>Week0whiteblood</th>
      <th>Week1whiteblood</th>
      <th>Week2whiteblood</th>
      <th>Week3whiteblood</th>
      <th>Week4whiteblood</th>
      <th>Week5whiteblood</th>
      <th>Week6whiteblood</th>
      <th>Week7whiteblood</th>
      <th>Week8whiteblood</th>
      <th>Week9whiteblood</th>
      <th>Week10whiteblood</th>
      <th>Week11whiteblood</th>
      <th>Week12whiteblood</th>
      <th>Week0lymphocytes</th>
      <th>Week1lymphocytes</th>
      <th>Week2lymphocytes</th>
      <th>Week3lymphocytes</th>
      <th>Week4lymphocytes</th>
      <th>Week5lymphocytes</th>
      <th>Week6lymphocytes</th>
      <th>Week7lymphocytes</th>
      <th>Week8lymphocytes</th>
      <th>Week9lymphocytes</th>
      <th>Week10lymphocytes</th>
      <th>Week11lymphocytes</th>
      <th>Week12lymphocytes</th>
      <th>Week1pcv</th>
      <th>Week2pcv</th>
      <th>Week3pcv</th>
      <th>Week4pcv</th>
      <th>Week5pcv</th>
      <th>Week6pcv</th>
      <th>Week7pcv</th>
      <th>Week8pcv</th>
      <th>Week9pcv</th>
      <th>Week10pcv</th>
      <th>Week11pcv</th>
      <th>Week12pcv</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @observationbiometrics.each do |observationbiometric| %>
      <tr>
        <td><%= observationbiometric.treatment_id %></td>
        <td><%= observationbiometric.Day0TempF %></td>
        <td><%= observationbiometric.Day1TempF %></td>
        <td><%= observationbiometric.Day2TempF %></td>
        <td><%= observationbiometric.Day3TempF %></td>
        <td><%= observationbiometric.Day4TempF %></td>
        <td><%= observationbiometric.Day5TempF %></td>
        <td><%= observationbiometric.Week0WhiteBlood %></td>
        <td><%= observationbiometric.Week1WhiteBlood %></td>
        <td><%= observationbiometric.Week2WhiteBlood %></td>
        <td><%= observationbiometric.Week3WhiteBlood %></td>
        <td><%= observationbiometric.Week4WhiteBlood %></td>
        <td><%= observationbiometric.Week5WhiteBlood %></td>
        <td><%= observationbiometric.Week6WhiteBlood %></td>
        <td><%= observationbiometric.Week7WhiteBlood %></td>
        <td><%= observationbiometric.Week8WhiteBlood %></td>
        <td><%= observationbiometric.Week9WhiteBlood %></td>
        <td><%= observationbiometric.Week10WhiteBlood %></td>
        <td><%= observationbiometric.Week11WhiteBlood %></td>
        <td><%= observationbiometric.Week12WhiteBlood %></td>
        <td><%= observationbiometric.Week0lymphocytes %></td>
        <td><%= observationbiometric.Week1lymphocytes %></td>
        <td><%= observationbiometric.Week2lymphocytes %></td>
        <td><%= observationbiometric.Week3lymphocytes %></td>
        <td><%= observationbiometric.Week4lymphocytes %></td>
        <td><%= observationbiometric.Week5lymphocytes %></td>
        <td><%= observationbiometric.Week6lymphocytes %></td>
        <td><%= observationbiometric.Week7lymphocytes %></td>
        <td><%= observationbiometric.Week8lymphocytes %></td>
        <td><%= observationbiometric.Week9lymphocytes %></td>
        <td><%= observationbiometric.Week10lymphocytes %></td>
        <td><%= observationbiometric.Week11lymphocytes %></td>
        <td><%= observationbiometric.Week12lymphocytes %></td>
        <td><%= observationbiometric.Week1PCV %></td>
        <td><%= observationbiometric.Week2PCV %></td>
        <td><%= observationbiometric.Week3PCV %></td>
        <td><%= observationbiometric.Week4PCV %></td>
        <td><%= observationbiometric.Week5PCV %></td>
        <td><%= observationbiometric.Week6PCV %></td>
        <td><%= observationbiometric.Week7PCV %></td>
        <td><%= observationbiometric.Week8PCV %></td>
        <td><%= observationbiometric.Week9PCV %></td>
        <td><%= observationbiometric.Week10PCV %></td>
        <td><%= observationbiometric.Week11PCV %></td>
        <td><%= observationbiometric.Week12PCV %></td>
        <td><%= link_to 'Show', observationbiometric %></td>
        <td><%= link_to 'Edit', edit_observationbiometric_path(observationbiometric) %></td>
        <td><%= link_to 'Destroy', observationbiometric, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Observationbiometric', new_observationbiometric_path %>

app/views/observationbiometrics/new.html.erb
<h1>New Observationbiometric</h1>

<%= render 'form' %>

<%= link_to 'Back', observationbiometrics_path %>

app/views/observationbiometrics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_observationbiometric_path(@observationbiometric) %> 
|
<%= link_to 'View all observation biometrics', observationbiometrics_path %> | 
<a href='/treatments/<%= @observationbiometric.treatment_id %>'>Back</a> 

<p>
  <strong>Treatment:</strong>
  <%= @observationbiometric.treatment_id %>
</p>

<p>
  <strong>Day0tempf:</strong>
  <%= @observationbiometric.Day0TempF %>
</p>

<p>
  <strong>Day1tempf:</strong>
  <%= @observationbiometric.Day1TempF %>
</p>

<p>
  <strong>Day2tempf:</strong>
  <%= @observationbiometric.Day2TempF %>
</p>

<p>
  <strong>Day3tempf:</strong>
  <%= @observationbiometric.Day3TempF %>
</p>

<p>
  <strong>Day4tempf:</strong>
  <%= @observationbiometric.Day4TempF %>
</p>

<p>
  <strong>Day5tempf:</strong>
  <%= @observationbiometric.Day5TempF %>
</p>

<p>
  <strong>Week0whiteblood:</strong>
  <%= @observationbiometric.Week0WhiteBlood %>
</p>

<p>
  <strong>Week1whiteblood:</strong>
  <%= @observationbiometric.Week1WhiteBlood %>
</p>

<p>
  <strong>Week2whiteblood:</strong>
  <%= @observationbiometric.Week2WhiteBlood %>
</p>

<p>
  <strong>Week3whiteblood:</strong>
  <%= @observationbiometric.Week3WhiteBlood %>
</p>

<p>
  <strong>Week4whiteblood:</strong>
  <%= @observationbiometric.Week4WhiteBlood %>
</p>

<p>
  <strong>Week5whiteblood:</strong>
  <%= @observationbiometric.Week5WhiteBlood %>
</p>

<p>
  <strong>Week6whiteblood:</strong>
  <%= @observationbiometric.Week6WhiteBlood %>
</p>

<p>
  <strong>Week7whiteblood:</strong>
  <%= @observationbiometric.Week7WhiteBlood %>
</p>

<p>
  <strong>Week8whiteblood:</strong>
  <%= @observationbiometric.Week8WhiteBlood %>
</p>

<p>
  <strong>Week9whiteblood:</strong>
  <%= @observationbiometric.Week9WhiteBlood %>
</p>

<p>
  <strong>Week10whiteblood:</strong>
  <%= @observationbiometric.Week10WhiteBlood %>
</p>

<p>
  <strong>Week11whiteblood:</strong>
  <%= @observationbiometric.Week11WhiteBlood %>
</p>

<p>
  <strong>Week12whiteblood:</strong>
  <%= @observationbiometric.Week12WhiteBlood %>
</p>

<p>
  <strong>Week0lymphocytes:</strong>
  <%= @observationbiometric.Week0lymphocytes %>
</p>

<p>
  <strong>Week1lymphocytes:</strong>
  <%= @observationbiometric.Week1lymphocytes %>
</p>

<p>
  <strong>Week2lymphocytes:</strong>
  <%= @observationbiometric.Week2lymphocytes %>
</p>

<p>
  <strong>Week3lymphocytes:</strong>
  <%= @observationbiometric.Week3lymphocytes %>
</p>

<p>
  <strong>Week4lymphocytes:</strong>
  <%= @observationbiometric.Week4lymphocytes %>
</p>

<p>
  <strong>Week5lymphocytes:</strong>
  <%= @observationbiometric.Week5lymphocytes %>
</p>

<p>
  <strong>Week6lymphocytes:</strong>
  <%= @observationbiometric.Week6lymphocytes %>
</p>

<p>
  <strong>Week7lymphocytes:</strong>
  <%= @observationbiometric.Week7lymphocytes %>
</p>

<p>
  <strong>Week8lymphocytes:</strong>
  <%= @observationbiometric.Week8lymphocytes %>
</p>

<p>
  <strong>Week9lymphocytes:</strong>
  <%= @observationbiometric.Week9lymphocytes %>
</p>

<p>
  <strong>Week10lymphocytes:</strong>
  <%= @observationbiometric.Week10lymphocytes %>
</p>

<p>
  <strong>Week11lymphocytes:</strong>
  <%= @observationbiometric.Week11lymphocytes %>
</p>

<p>
  <strong>Week12lymphocytes:</strong>
  <%= @observationbiometric.Week12lymphocytes %>
</p>

<p>
  <strong>Week1pcv:</strong>
  <%= @observationbiometric.Week1PCV %>
</p>

<p>
  <strong>Week2pcv:</strong>
  <%= @observationbiometric.Week2PCV %>
</p>

<p>
  <strong>Week3pcv:</strong>
  <%= @observationbiometric.Week3PCV %>
</p>

<p>
  <strong>Week4pcv:</strong>
  <%= @observationbiometric.Week4PCV %>
</p>

<p>
  <strong>Week5pcv:</strong>
  <%= @observationbiometric.Week5PCV %>
</p>

<p>
  <strong>Week6pcv:</strong>
  <%= @observationbiometric.Week6PCV %>
</p>

<p>
  <strong>Week7pcv:</strong>
  <%= @observationbiometric.Week7PCV %>
</p>

<p>
  <strong>Week8pcv:</strong>
  <%= @observationbiometric.Week8PCV %>
</p>

<p>
  <strong>Week9pcv:</strong>
  <%= @observationbiometric.Week9PCV %>
</p>

<p>
  <strong>Week10pcv:</strong>
  <%= @observationbiometric.Week10PCV %>
</p>

<p>
  <strong>Week11pcv:</strong>
  <%= @observationbiometric.Week11PCV %>
</p>

<p>
  <strong>Week12pcv:</strong>
  <%= @observationbiometric.Week12PCV %>
</p>